package GUI;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class GUI_DataMahasiswa extends javax.swing.JFrame {

    public GUI_DataMahasiswa() { //Konstruktor//
        initComponents();
        this.setTitle("Aplikasi Data Mahasiswa");
        this.setLocationRelativeTo(this);
        
        Koneksi konek= new Koneksi();
        konek.koneksi();
        this.StatusKoneksi.setText(konek.StatusKoneksi);
        
        tabelData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputData = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inNIM = new javax.swing.JTextField();
        inNama = new javax.swing.JTextField();
        inPerempuan = new javax.swing.JRadioButton();
        inLakilaki = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        inAktif = new javax.swing.JRadioButton();
        inNonAktif = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        inAlamat = new javax.swing.JTextArea();
        inAgama = new javax.swing.JComboBox<>();
        inNoHp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        inProdi = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        StatusKoneksi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inCari = new javax.swing.JButton();
        inPencarian = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputData.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("INPUT DATA MAHASISWA");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("NIM");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Nama");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Jenis Kelamin");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Nomor HP");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Agama");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Status");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        inNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inNIMActionPerformed(evt);
            }
        });

        inPerempuan.setText("Perempuan");

        inLakilaki.setText("Laki-Laki");
        inLakilaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inLakilakiActionPerformed(evt);
            }
        });

        jLabel10.setText("Alamat");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        inAktif.setText("Aktif");

        inNonAktif.setText("Tidak Aktif");

        inAlamat.setColumns(20);
        inAlamat.setRows(5);
        jScrollPane2.setViewportView(inAlamat);

        inAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Agama-", "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Konghucu" }));
        inAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inAgamaActionPerformed(evt);
            }
        });

        jLabel11.setText("Prodi");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        inProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Prodi-", "Teknik Sipil", "Teknik Mesin", "Peternakan", "Matematika", "Ilmu Komputer", "Fisika", "Pendidikan Olah Raga", "Pendidikan Guru Sekolah Dasar", "Pendidikan Bahasa Inggris", "Pendidikan Bahasa Indonesia", "Psikologi Islam", "Perbankan Syariah", "Pendidikan Islam Anak Usia Dini", " Komunikasi Penyiaran Islam", "Hukum Keluarga Islam", "Ilmu Al-Quran dan Tafsir", "Ekonomi Syariah" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(inAktif)
                                .addGap(64, 64, 64)
                                .addComponent(inNonAktif))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(inNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inNama, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(inLakilaki)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inPerempuan))
                                .addComponent(inProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inLakilaki)
                    .addComponent(inPerempuan)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inNonAktif))))
                .addGap(17, 17, 17))
        );

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Reset");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Update");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Hapus");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("Status Koneksi");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inCari.setText("Cari");
        inCari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inCariActionPerformed(evt);
            }
        });

        inPencarian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Pencarian -", "NIM", "Nama", "Prodi", "Jenis Kelamin", "Nomor HP", "Agama", "Alamat", "Status" }));
        inPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPencarianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StatusKoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inCari, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inCari)
                    .addComponent(inPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(StatusKoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InputData.addTab("Input Data", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("   DATA MAHASISWA");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabelData.setAutoCreateRowSorter(true);
        tabelData.setBackground(new java.awt.Color(204, 204, 255));
        tabelData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Prodi", "Jenis Kelamin", "Nomor HP", "Agama", "Alamat", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelData.setShowGrid(true);
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelData);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        InputData.addTab("Tampilan Data", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputData)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputData)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

Statement pst ;
ResultSet rs;

 public void tabelData()
    {
        
        Koneksi konek = new Koneksi();
        konek.koneksi();
        
     try {
    String sql = "select*from datamahasiswa";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            
        }
    }

    public void selectByNIM(int nim) {
        Koneksi konek = new Koneksi();
        konek.koneksi();

        try {

            String sql = "select * from datamahasiswa where NIM like '%" + nim + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void selectByNama(String nama) {
        Koneksi konek = new Koneksi();
        konek.koneksi();

        try {

            String sql = "select * from datamahasiswa where Nama like '%" + nama + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

        public void selectByProdi(String prodi) {
        Koneksi konek = new Koneksi();
        konek.koneksi();

        try {

            String sql = "select * from datamahasiswa where Prodi like '%" + prodi + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void selectByJK(String jenis) {
        Koneksi konek = new Koneksi();
        konek.koneksi();

        try {

            String sql = "select * from datamahasiswa where Jenis_Kelamin like '%" + jenis + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }    
        
    }
        public void selectByNomorHP(String noHp) {
        Koneksi konek = new Koneksi();
        konek.koneksi();

        try {

            String sql = "select * from datamahasiswa where Nomor_HP like '%" + noHp + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
        public void selectByAgama(String agama) {
        Koneksi konek = new Koneksi();
        konek.koneksi();

        try {

            String sql = "select * from datamahasiswa where Agama like '%" + agama + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
        public void selectByAlamat(String alamat) {
        Koneksi konek = new Koneksi();
        konek.koneksi();

        try {

            String sql = "select * from datamahasiswa where Alamat like '%" + alamat + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }    
        
        public void selectByStatus(String status) {
        Koneksi konek = new Koneksi();
        konek.koneksi();

        try {

            String sql = "select * from datamahasiswa where Status like '%" + status + "%'";
//            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabelData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }
        
    private void inLakilakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inLakilakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inLakilakiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     
        String jenis = "";
        if (inLakilaki.isSelected()){
            jenis = "Laki-laki";
        }else if (inPerempuan.isSelected()){
            jenis = "Perempuan";
        }
        
        String status = "";
        if (inAktif.isSelected()){
            status = "Aktif";
        }else if (inNonAktif.isSelected()){
            status = "Non Aktif";
        }
        
        String prodi = "";         
        if (inProdi.getSelectedIndex() == 1) {
            prodi = "Teknik Sipil";
        } else if (inProdi.getSelectedIndex() == 2) {
            prodi = "Teknik Mesin";
        } else if (inProdi.getSelectedIndex() == 3) {
            prodi = "Peternakan";
        } else if (inProdi.getSelectedIndex() == 4) {
            prodi = "Matematika";
        } else if (inProdi.getSelectedIndex() == 5) {
            prodi = "Ilmu Komputer";
        } else if (inProdi.getSelectedIndex() == 6) {
            prodi = "Fisika";
        } else if (inProdi.getSelectedIndex() == 7) {
            prodi = "Pendidikan Olah Raga";
        } else if (inProdi.getSelectedIndex() == 8) {
            prodi = "Pendidikan Guru Sekolah Dasar";
        } else if (inProdi.getSelectedIndex() == 9) {
            prodi = "Pendidikan Bahasa Inggris";
        } else if (inProdi.getSelectedIndex() == 10) {
            prodi = "Pendidikan Bahasa Indonesia";
        } else if (inProdi.getSelectedIndex() == 11) {
            prodi = "Psikologi Islam";
        } else if (inProdi.getSelectedIndex() == 12) {
            prodi = "Perbankan Syariah";
        } else if (inProdi.getSelectedIndex() == 13) {
            prodi = "Pendidikan Islam Anak Usia Dini";
        } else if (inProdi.getSelectedIndex() == 14) {
            prodi = "Komunikasi Penyiaran Islam";
        } else if (inProdi.getSelectedIndex() == 15) {
            prodi = "Hukum Keluarga Islam";
        } else if (inProdi.getSelectedIndex() == 16) {
            prodi = "Ilmu Al-Quran dan Tafsir";
        } else if (inProdi.getSelectedIndex() == 17) {
            prodi = "Ekonomi Syariah";
        } else {
            return; 
        }
        
        String agama = ""; 
        if (inAgama.getSelectedIndex() == 1) {
            agama = "Islam";
        } else if (inAgama.getSelectedIndex() == 2) {
            agama = "Kristen";
        } else if (inAgama.getSelectedIndex() == 3) {
            agama = "Katolik";
        } else if (inAgama.getSelectedIndex() == 4) {
            agama = "Hindu";
        } else if (inAgama.getSelectedIndex() == 5) {
            agama = "Budha";
        } else if (inAgama.getSelectedIndex() == 6) {
            agama = "Konghucu";
        } else {
            return; 
        }
        
        int nim = Integer.parseInt(inNIM.getText());
        String nama = inNama.getText();
        String noHp = inNoHp.getText();
        String alamat = inAlamat.getText();
        
        Insert in = new Insert();
        in.insert(nim, nama, prodi, jenis, noHp, agama, alamat, status);
        tabelData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tabelData.getModel(); //create a model
        int selectedRowIndex = tabelData.getSelectedRow(); //get selected row
        int id = (int) dtm.getValueAt(selectedRowIndex, 0); //get the primary key to fetch data.

        Koneksi konek = new Koneksi();
        konek.koneksi();

        try {

            String sql = "select * from datamahasiswa where NIM like '%" + id + "%'";
            pst = konek.con.prepareStatement(sql);
            ResultSet rs = rs = pst.executeQuery(sql);   //u can use normal query
            
            while(rs.next()){    //u can use normal query
                inNIM.setText(rs.getString("NIM"));
                inNama.setText(rs.getString("Nama"));
                inNoHp.setText(rs.getString("Nomor_HP"));
                inAlamat.setText(rs.getString("Alamat"));
                
                String jenis = rs.getString("Jenis_Kelamin");
                if (jenis.equals("Laki-laki")) {
                    inLakilaki.setSelected(true);
                    inPerempuan.setSelected(false);
                } else {
                    inLakilaki.setSelected(false);
                    inPerempuan.setSelected(true);
                }
                          
                String status = rs.getString("Status");
                if (status.equals("Aktif")) {
                    inAktif.setSelected(true);
                    inNonAktif.setSelected(false);
                } else {
                    inAktif.setSelected(false);
                    inNonAktif.setSelected(true);
                    
                }
                
                String prodi = rs.getString("Prodi");
                if (prodi.equals("Teknik Sipil")) {
                    inProdi.setSelectedIndex(1);
                } else if (prodi.equals("Teknik Mesin")) {
                    inProdi.setSelectedIndex(2);
                } else if (prodi.equals("Peternakan")) {
                    inProdi.setSelectedIndex(3);
                } else if (prodi.equals("Matematika")) {
                    inProdi.setSelectedIndex(4);
                } else if (prodi.equals("Ilmu Komputer")) {
                    inProdi.setSelectedIndex(5);
                } else if (prodi.equals("Fisika")) {
                    inProdi.setSelectedIndex(6);
                } else if (prodi.equals("Pendidikan Olah Raga")) {
                    inProdi.setSelectedIndex(7);
                } else if (prodi.equals("Pendidikan Guru Sekolah Dasar")) {
                    inProdi.setSelectedIndex(8);
                } else if (prodi.equals("Pendidikan Bahasa Inggris")) {
                    inProdi.setSelectedIndex(9);
                } else if (prodi.equals("Pendidikan Bahasa Indonesia")) {
                    inProdi.setSelectedIndex(10);
                } else if (prodi.equals("Psikologi Islam")) {
                    inProdi.setSelectedIndex(11);
                } else if (prodi.equals("Perbankan Syariah")) {
                    inProdi.setSelectedIndex(12);
                } else if (prodi.equals("Pendidikan Islam Anak Usia Dini")) {
                    inProdi.setSelectedIndex(13);
                } else if (prodi.equals("Komunikasi Penyiaran Islam")) {
                    inProdi.setSelectedIndex(14);
                } else if (prodi.equals("Hukum Keluarga Islam")) {
                    inProdi.setSelectedIndex(15);
                } else if (prodi.equals("Ilmu Al-Quran dan Tafsir")) {
                    inProdi.setSelectedIndex(16);
                } else if (prodi.equals("Ekonomi Syariah")) {
                    inProdi.setSelectedIndex(17);
                } else {
                    inProdi.setSelectedIndex(0);
                }
                
                String agama = rs.getString("Agama");
                if (agama.equals("Islam")) {
                    inAgama.setSelectedIndex(1);
                } else if (agama.equals("Kristen")) {
                    inAgama.setSelectedIndex(2);
                } else if (agama.equals("Katolik")) {
                    inAgama.setSelectedIndex(3);
                } else if (agama.equals("Hindu")) {
                    inAgama.setSelectedIndex(4);
                } else if (agama.equals("Budha")) {
                    inAgama.setSelectedIndex(5);
                } else if (agama.equals("Konghucu")) {
                    inAgama.setSelectedIndex(6);
                } else {
                    inAgama.setSelectedIndex(0);
                }
            }
        } catch (Exception ex) {
            
        }

    }//GEN-LAST:event_tabelDataMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Koneksi konek = new Koneksi();
        konek.koneksi();
        Delete del = new Delete();
        del.delete(Integer.parseInt(inNIM.getText()));
        
        tabelData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Koneksi konek = new Koneksi();
        konek.koneksi();
        
        String jenis = "";
        if (inLakilaki.isSelected()){
            jenis = "Laki-laki";
        }else if (inPerempuan.isSelected()){
            jenis = "Perempuan";
        }
        
        String status = "";
        if (inAktif.isSelected()){
            status = "Aktif";
        }else if (inNonAktif.isSelected()){
            status = "Non Aktif";
        }
        
        String prodi = "";         
        if (inProdi.getSelectedIndex() == 1) {
            prodi = "Teknik Sipil";
        } else if (inProdi.getSelectedIndex() == 2) {
            prodi = "Teknik Mesin";
        } else if (inProdi.getSelectedIndex() == 3) {
            prodi = "Peternakan";
        } else if (inProdi.getSelectedIndex() == 4) {
            prodi = "Matematika";
        } else if (inProdi.getSelectedIndex() == 5) {
            prodi = "Ilmu Komputer";
        } else if (inProdi.getSelectedIndex() == 6) {
            prodi = "Fisika";
        } else if (inProdi.getSelectedIndex() == 7) {
            prodi = "Pendidikan Olah Raga";
        } else if (inProdi.getSelectedIndex() == 8) {
            prodi = "Pendidikan Guru Sekolah Dasar";
        } else if (inProdi.getSelectedIndex() == 9) {
            prodi = "Pendidikan Bahasa Inggris";
        } else if (inProdi.getSelectedIndex() == 10) {
            prodi = "Pendidikan Bahasa Indonesia";
        } else if (inProdi.getSelectedIndex() == 11) {
            prodi = "Psikologi Islam";
        } else if (inProdi.getSelectedIndex() == 12) {
            prodi = "Perbankan Syariah";
        } else if (inProdi.getSelectedIndex() == 13) {
            prodi = "Pendidikan Islam Anak Usia Dini";
        } else if (inProdi.getSelectedIndex() == 14) {
            prodi = "Komunikasi Penyiaran Islam";
        } else if (inProdi.getSelectedIndex() == 15) {
            prodi = "Hukum Keluarga Islam";
        } else if (inProdi.getSelectedIndex() == 16) {
            prodi = "Ilmu Al-Quran dan Tafsir";
        } else if (inProdi.getSelectedIndex() == 17) {
            prodi = "Ekonomi Syariah";
        } else {
            return; 
        }
        
        String agama = ""; 
        if (inAgama.getSelectedIndex() == 1) {
            agama = "Islam";
        } else if (inAgama.getSelectedIndex() == 2) {
            agama = "Kristen";
        } else if (inAgama.getSelectedIndex() == 3) {
            agama = "Katolik";
        } else if (inAgama.getSelectedIndex() == 4) {
            agama = "Hindu";
        } else if (inAgama.getSelectedIndex() == 5) {
            agama = "Budha";
        } else if (inAgama.getSelectedIndex() == 6) {
            agama = "Konghucu";
        } else {
            return; 
        }

        int nim = Integer.parseInt(inNIM.getText());
        String nama = inNama.getText();
        String noHp = inNoHp.getText();
        String alamat = inAlamat.getText();

        Update ubah = new Update();
        ubah.Update(nim, nama, prodi, jenis, noHp, agama, alamat, status);

        tabelData();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        inNIM.setText("");
        inNama.setText("");
        inAlamat.setText("");
        inNoHp.setText("");
        
        inLakilaki.setSelected(false);
        inPerempuan.setSelected(false);
                          
    
        inAktif.setSelected(false);
        inNonAktif.setSelected(false);
    
        inProdi.setSelectedIndex(0);
        inAgama.setSelectedIndex(0);
        inPencarian.setSelectedIndex(0);
        
        tabelData();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void inAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inAgamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inAgamaActionPerformed

    private void inCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inCariActionPerformed
        // TODO add your handling code here:
        if (inPencarian.getSelectedIndex() == 1) {
            selectByNIM(Integer.parseInt(inNIM.getText()));
        } else if (inPencarian.getSelectedIndex() == 2) {
            selectByNama(inNama.getText());
        } else if (inPencarian.getSelectedIndex() == 3) {
            
            String prodi = "";         
                if (inProdi.getSelectedIndex() == 1) {
                    prodi = "Teknik Sipil";
                } else if (inProdi.getSelectedIndex() == 2) {
                    prodi = "Teknik Mesin";
                } else if (inProdi.getSelectedIndex() == 3) {
                    prodi = "Peternakan";
                } else if (inProdi.getSelectedIndex() == 4) {
                    prodi = "Matematika";
                } else if (inProdi.getSelectedIndex() == 5) {
                    prodi = "Ilmu Komputer";
                } else if (inProdi.getSelectedIndex() == 6) {
                    prodi = "Fisika";
                } else if (inProdi.getSelectedIndex() == 7) {
                    prodi = "Pendidikan Olah Raga";
                } else if (inProdi.getSelectedIndex() == 8) {
                    prodi = "Pendidikan Guru Sekolah Dasar";
                } else if (inProdi.getSelectedIndex() == 9) {
                    prodi = "Pendidikan Bahasa Inggris";
                } else if (inProdi.getSelectedIndex() == 10) {
                    prodi = "Pendidikan Bahasa Indonesia";
                } else if (inProdi.getSelectedIndex() == 11) {
                    prodi = "Psikologi Islam";
                } else if (inProdi.getSelectedIndex() == 12) {
                    prodi = "Perbankan Syariah";
                } else if (inProdi.getSelectedIndex() == 13) {
                    prodi = "Pendidikan Islam Anak Usia Dini";
                } else if (inProdi.getSelectedIndex() == 14) {
                    prodi = "Komunikasi Penyiaran Islam";
                } else if (inProdi.getSelectedIndex() == 15) {
                    prodi = "Hukum Keluarga Islam";
                } else if (inProdi.getSelectedIndex() == 16) {
                    prodi = "Ilmu Al-Quran dan Tafsir";
                } else if (inProdi.getSelectedIndex() == 17) {
                    prodi = "Ekonomi Syariah";
                } else {
                }
                
                selectByProdi(prodi);
        } else if (inPencarian.getSelectedIndex() == 4) {
            
            String jenis = "";
            if (inLakilaki.isSelected()) {
                jenis = "Laki-laki";
            } else if (inPerempuan.isSelected()) {
                jenis = "Perempuan";
            }
            
            selectByJK(jenis);
        } else if (inPencarian.getSelectedIndex() == 5) {
            selectByNomorHP(inNoHp.getText());
        } else if (inPencarian.getSelectedIndex() == 6) {    
            
            String agama = ""; 
                if (inAgama.getSelectedIndex() == 1) {
                    agama = "Islam";
                } else if (inAgama.getSelectedIndex() == 2) {
                    agama = "Kristen";
                } else if (inAgama.getSelectedIndex() == 3) {
                    agama = "Katolik";
                } else if (inAgama.getSelectedIndex() == 4) {
                    agama = "Hindu";
                } else if (inAgama.getSelectedIndex() == 5) {
                    agama = "Budha";
                } else if (inAgama.getSelectedIndex() == 6) {
                    agama = "Konghucu";
                } else {
                    return; 
                }
                
            selectByAgama(agama); 
        } else if (inPencarian.getSelectedIndex() == 7) {
            selectByAlamat(inAlamat.getText());  
        } else if (inPencarian.getSelectedIndex() == 8) {
            
            String status = "";
            if (inAktif.isSelected()){
                status = "Aktif";
            }else if (inNonAktif.isSelected()){
                status = "Non Aktif";
            }
            
            selectByStatus(status);
        } else {
            tabelData();
        }
    }//GEN-LAST:event_inCariActionPerformed

    private void inPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPencarianActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inPencarianActionPerformed

    private void inNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inNIMActionPerformed

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_DataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane InputData;
    private javax.swing.JTextField StatusKoneksi;
    private javax.swing.JComboBox<String> inAgama;
    private javax.swing.JRadioButton inAktif;
    private javax.swing.JTextArea inAlamat;
    private javax.swing.JButton inCari;
    private javax.swing.JRadioButton inLakilaki;
    private javax.swing.JTextField inNIM;
    private javax.swing.JTextField inNama;
    private javax.swing.JTextField inNoHp;
    private javax.swing.JRadioButton inNonAktif;
    private javax.swing.JComboBox<String> inPencarian;
    private javax.swing.JRadioButton inPerempuan;
    private javax.swing.JComboBox<String> inProdi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelData;
    // End of variables declaration//GEN-END:variables
}
